services:
  webapp:
      build: .
      ports:
        - "8000:8000"
      environment:
        - DB_USER=calc
        - DB_PASSWORD=calc
        - DB_NAME=calc_db
        - DB_HOST=db
      command: ["poetry", "run", "uvicorn", "--host", "0.0.0.0", "simple_async_calculator.api.handlers:app", "--reload"]
      volumes:
        - ./:/app/
      depends_on:
        - db

  db:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=calc
      - POSTGRES_PASSWORD=calc
      - POSTGRES_DB=calc_db

