services:
  tests: &base
      build:
        context: .
        dockerfile: docker/test.Dockerfile
      ports:
        - "8000:8000"
      environment:
        - DB_USER=calc
        - DB_PASSWORD=calc
        - DB_NAME=calc_db
        - DB_HOST=db
      command: ["sh", "shell/runtests.sh"]
      volumes:
        - ./:/app/
      depends_on:
        - db
  webapp:
      <<: *base
      build:
        context: .
        dockerfile: docker/dev.Dockerfile
      ports:
        - "8000:8000"
      command: ["make", "runserver", "env=dev"]

  db:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=calc
      - POSTGRES_PASSWORD=calc
      - POSTGRES_DB=calc_db

