[tool.pylint]
disable = "missing-module-docstring"

[tool.poetry]
name = "simple-async-calculator"
version = "0.1.0"
description = ""
authors = ["Андрей Леонтьев <andruwwwka@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.87.0"
click = "^8.1.3"
uvicorn = "^0.20.0"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.6"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
