[tool.poetry]
name = "simple-async-calculator"
version = "0.1.0"
description = ""
authors = ["Андрей Леонтьев <andruwwwka@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.87.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
