version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
loggers:
  uvicorn:
    level: INFO
    handlers:
      - default
    propagate: no
  cron:
    level: DEBUG
    handlers:
      - default
    propagate: no
  api:
    level: DEBUG
    handlers:
      - default
    propagate: no