name: Code quality
on:
  pull_request:
    types:
      - labeled
jobs:
  check_label:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ startsWith(github.event.label.name, 'formatted') }}
        runs: echo "Run code quality checks"
  pylint:
    needs: check_label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: poetry install --with pylint --without dev
      - run: poetry run pylint --recursive=y .
  mypy:
    needs: check_label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: poetry install --with mypy --without dev
      - run: poetry run mypy .
  remove_label:
    needs:
      - mypy
      - pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: formatted
