name: Code quality
on: [pull_request]
jobs:
  pylint:
    runs-on: ubuntu-latest
    name: Run pylint checks
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Poetry
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: make install-deps deps=pylint,test
      - name: Run pylint checker
        run: make pylint
  mypy:
    runs-on: ubuntu-latest
    name: Run mypy checks
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: make install-deps deps=mypy,test
      - name: Run mypy checker
        run: make mypy
  test:
    runs-on: ubuntu-latest
    name: Run tests and collect coverage report
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: make install-deps deps=test
      - name: Collect coverage
        id: coverage
        run: |
          make test
          cov_fail=`cat ./pytest-coverage.txt | grep 'is less than fail-under'` || echo ''
          echo "cov_fail=$cov_fail" >> $GITHUB_OUTPUT
          test_fails=`cat ./pytest.xml | grep '</failure>'` || echo ''
          echo "test_fails=$test_fails" >> $GITHUB_OUTPUT
          test_errors=`cat ./pytest.xml | grep '</error>'` || echo ''
          echo "test_errors=$test_errors" >> $GITHUB_OUTPUT
      - name: Check bad tests report
        if: |
          steps.coverage.outputs.cov_fail || steps.coverage.outputs.test_fails || steps.coverage.outputs.test_errors
        run: exit 1
      - name: Coverage report comment
        if: failure()
        uses: MishaKav/pytest-coverage-comment@main
        with:
          junitxml-path: ./pytest.xml
          create-new-comment: true
      - name: Pull request failure message
        uses: ntsd/auto-request-changes-action@v2
        if: failure()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-body: Auto checks failed
      - name: Pull request success message
        uses: hmarr/auto-approve-action@v3
        if: success()
        with:
          review-message: Auto checks succeed
  formatter:
    name: Autoformat source code
    needs:
      - mypy
      - pylint
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install isort
        run: pip install isort
      - name: Install black
        run: pip install black
      - name: Run formatter
        run: make formatter
      - name: Check changed files
        id: git-diff
        run: |
          diff_list=`git diff --name-only`
          echo "diff=$diff_list" >> $GITHUB_OUTPUT
      - name: Autoformat commit
        if: steps.git-diff.outputs.diff
        run: |
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'          
          git commit -am "[GitHub Actions] Format Python code with psf/black and PyCQA/isort"
          git push

