name: Code quality
on: [pull_request]
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: poetry install --with pylint,test --without dev
      - run: poetry run pylint --recursive=y .
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: poetry install --with mypy,test --without dev
      - run: poetry run mypy .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: poetry install --with test --without dev
      - name: Collect coverage
        id: coverage
        run: |
          poetry run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=src --cov-fail-under=100 | tee pytest-coverage.txt
          cov_fail=`cat ./pytest-coverage.txt | grep 'not reached'` || echo ''
          echo "cov_fail=$cov_fail" >> $GITHUB_OUTPUT
      - if: steps.coverage.outputs.cov_fail
        run: exit 1
      - name: Coverage comment
        if: failure()
        uses: MishaKav/pytest-coverage-comment@main
        with:
          junitxml-path: ./pytest.xml
          create-new-comment: true
  formatter:
    needs:
      - mypy
      - pylint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install isort
      - run: isort .
      - run: pip install black
      - run: black .
      - id: git-diff
        run: |
          diff_list=`git diff --name-only`
          echo "diff=$diff_list" >> $GITHUB_OUTPUT
      - if: steps.git-diff.outputs.diff
        run: |
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'          
          git commit -am "[GitHub Actions] Format Python code with psf/black and PyCQA/isort"
          git push

