name: Production deployment
on: [workflow_dispatch]
env:
  DOCKER_IMAGE: andruwwwka/simple-async-calc
  DOCKER_REGISTRY: docker.io
jobs:
  build:
    name: Build image
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: "$DOCKER_IMAGE"
          registry: "$DOCKER_REGISTRY"
          addLatest: true
          dockerfile: docker/prod.Dockerfile
          username: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
          password: ${{ secrets.DOCKER_REGISTRY_PWD }}
  deploy:
    name: Deploy production
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Configure ssh client
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Docker login
        run: ssh -o "StrictHostKeyChecking=no" ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} docker login -u ${{ secrets.DOCKER_REGISTRY_LOGIN }} -p ${{ secrets.DOCKER_REGISTRY_PWD }} "$DOCKER_REGISTRY"
      - name: Pull Docker image
        run: ssh ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} docker-compose pull webapp
      - name: Deploy
        run: ssh ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} docker-compose up -d
