name: Production deployment
on: [workflow_dispatch]
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Build image
        run: docker build -f docker/prod.Dockerfile -t simple-async-calc .
      - name: Docker login
        env:
          DOCKER_REGISTRY_PWD: ${{ secrets.DOCKER_REGISTRY_PWD }}
          DOCKER_REGISTRY_LOGIN: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
        run: docker login -u "$DOCKER_REGISTRY_LOGIN" -p "$DOCKER_REGISTRY_PWD"