name: Production deployment
on: [workflow_dispatch]
env:
  DOCKER_REGISTRY_PWD: ${{ secrets.DOCKER_REGISTRY_PWD }}
  DOCKER_REGISTRY_LOGIN: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Build image
        run: docker build -f docker/prod.Dockerfile -t simple-async-calc .
      - name: Docker login
        run: docker login -u "$DOCKER_REGISTRY_LOGIN" -p "$DOCKER_REGISTRY_PWD"
      - name: Tag image
        run: docker tag simple-async-calc "$DOCKER_REGISTRY_LOGIN"/simple-async-calc:${{ github.sha }}
      - name: Push image
        run: docker push "$DOCKER_REGISTRY_LOGIN"/simple-async-calc:${{ github.sha }}