name: Production deployment
on: [workflow_dispatch]
env:
  DOCKER_REGISTRY_PWD: ${{ secrets.DOCKER_REGISTRY_PWD }}
  DOCKER_REGISTRY_LOGIN: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Build image
        run: docker build -f docker/prod.Dockerfile -t andruwwwka/simple-async-calc:latest .
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: andruwwwka/simple-async-calc
          registry: docker.io
          addLatest: true
          dockerfile: docker/prod.Dockerfile
          username: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
          password: ${{ secrets.DOCKER_REGISTRY_PWD }}