name: Production deployment
on: [workflow_dispatch]
env:
  DOCKER_REGISTRY_PWD: ${{ secrets.DOCKER_REGISTRY_PWD }}
  DOCKER_REGISTRY_LOGIN: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
  DOCKER_IMAGE: docker.io
  DOCKER_REGISTRY: andruwwwka/simple-async-calc
  PROD_USER: ${{ secrets.PROD_USER }}
  PROD_HOST: ${{ secrets.PROD_HOST }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: "$DOCKER_IMAGE"
          registry: "$DOCKER_REGISTRY"
          addLatest: true
          dockerfile: docker/prod.Dockerfile
          username: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
          password: ${{ secrets.DOCKER_REGISTRY_PWD }}
  deploy:
    name: Deploy production
    runs-on: ubuntu-latest
    steps:
      - name: Configure ssh client
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Docker login
        run: ssh ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} docker login -u "$DOCKER_REGISTRY_LOGIN" -p "$DOCKER_REGISTRY_PWD" "$DOCKER_REGISTRY"
      - name: Pull Docker image
        run: ssh "$PROD_USER"@"$PROD_HOST" docker-compose pull webapp
      - name: Deploy
        run: ssh "$PROD_USER"@"$PROD_HOST" docker-compose up -d
