name: Production deployment
on: [workflow_dispatch]
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        run: docker build -f docker/prod.Dockerfile -t simple-async-calc .
      - name: Docker login
        with:
          DOCKER_REGISTRY_PWD: ${{ secrets.DOCKER_REGISTRY_PWD }}
        run: docker login 185.241.195.143 --username registry --password DOCKER_REGISTRY_PWD
      - name: Push image
        run: docker push simple-async-calc