name: Pull request actions
on: [pull_request]
jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          use-pycodestyle: false
          use-flake8: false
          use-black: false
          use-isort: false
          extra-pylint-options: "--recursive=y"
