name: Push actions
on: [push]
jobs:
  formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install isort
      - run: isort .
      - run: pip install black
      - run: black --check .
        id: black_check
        continue-on-error: true
      - if: steps.black_check.outcome != 'success'
        run: |
          black .
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'          
          # git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git commit -am "[GitHub Actions] Format Python code with psf/black and PyCQA/isort"
          git push  # --force origin HEAD:$GITHUB_REF
